baseURL: /
title: NaruseJunのメモ帳

googleAnalytics: UA-44127552-3
defaultContentLanguage: ja
hasCJKLanguage: true

buildFuture: true

theme: narusejun

markup:
  goldmark:
    renderer:
      hardWraps: true
  highlight:
    codeFences: false

params:
  author: NaruseJun
  subtitle: NaruseJunがいろいろ書いてる
  description: NaruseJunのメモ帳

  customImage: https://res.cloudinary.com/narusejun/image/twitter_name/sekai67.jpg

  github: https://github.com/kaz
  twitter: https://twitter.com/sekai67
  facebook: https://www.facebook.com/sawada.kazuki

  copyrightBy: NaruseJun
  copyrightUrl: /

  creditsText: " "
  creditsUrl: /
