version: 2
jobs:
  build:
    working_directory: /tmp/blog
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Sync submodules
          command: |
            git submodule sync
            git submodule update --init
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate pages
          command: |
            ./node_modules/.bin/hexo clean
            ./node_modules/.bin/hexo generate
      - run:
          name: Archive pages
          command: tar zcvf public.tar.gz public
      - store_artifacts:
          path: /tmp/blog/public.tar.gz
          destination: public.tar.gz
      - deploy:
          name: Deploy to server
          command: |
            scp -o "StrictHostKeyChecking=no" public.tar.gz http@narusejun.com:/tmp
            ssh -o "StrictHostKeyChecking=no" http@narusejun.com "tar zxvf /tmp/public.tar.gz -C /tmp && rm -rf ~/narusejun.com && mv /tmp/public ~/narusejun.com && rm /tmp/public.tar.gz"
