name: deploy

on:
  push:
    branches:
      - master

env:
  GIT_COMMIT_SHA: ${{ github.sha }}
  GIT_REMOTE: https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git
  GIT_BRANCH: gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/cache@v2
        with:
          key: cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          path: |
            **/.next/cache
            **/node_modules
      - run: ./tasks.sh build
      - run: ./tasks.sh deploy
